# Generated by Django 6.1 on 2026-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название мастеркласса')),
                ('tamada', models.CharField(max_length=128, verbose_name='Ведущий')),
                ('date', models.DateField(verbose_name='Дата мастеркалсса')),
                ('time', models.TimeField(verbose_name='Время мастеркласса')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.TextField(verbose_name='Цена')),
                ('place', models.CharField(max_length=64, verbose_name='Кол-во мест')),
            ],
            options={
                'verbose_name': 'Мастеркласс',
                'verbose_name_plural': 'Мастерклассы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news', verbose_name='Фото для новости')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(upload_to='portraits', verbose_name='Портрет')),
                ('name', models.CharField(max_length=128, verbose_name='Имя партнера')),
                ('profession', models.CharField(max_length=256, verbose_name='Профессия партнера')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('photo1', models.ImageField(upload_to='product_photo', verbose_name='Фото 1')),
                ('photo2', models.ImageField(upload_to='product_photo', verbose_name='Фото 2')),
                ('photo3', models.ImageField(upload_to='product_photo', verbose_name='Фото 3')),
                ('photo4', models.ImageField(upload_to='product_photo', verbose_name='Фото 4')),
                ('photo5', models.ImageField(upload_to='product_photo', verbose_name='Фото 5')),
                ('photo6', models.ImageField(upload_to='product_photo', verbose_name='Фото 6')),
                ('price', models.CharField(max_length=128, verbose_name='Цена')),
                ('desc', models.TextField(verbose_name='Описание продукта')),
                ('size', models.CharField(max_length=128, verbose_name='Размер товара')),
                ('details', models.TextField(verbose_name='Детали')),
            ],
        ),
    ]
