# Generated by Django 6.1 on 2026-08-18 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='photo',
            field=models.ImageField(default='', upload_to='masterclasses_photo', verbose_name='Фото мероприятия'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.productcategory'),
        ),
    ]
