# Generated by Django 6.1 on 2026-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclasses',
            name='photo',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото мероприятия'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото для новости'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='portrait',
            field=models.ImageField(upload_to='media', verbose_name='Портрет'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo1',
            field=models.ImageField(upload_to='media', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo2',
            field=models.ImageField(upload_to='media', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo3',
            field=models.ImageField(upload_to='media', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo4',
            field=models.ImageField(upload_to='media', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo5',
            field=models.ImageField(upload_to='media', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo6',
            field=models.ImageField(upload_to='media', verbose_name='Фото 6'),
        ),
    ]
