# Generated by Django 6.1 on 2026-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_masterclasses_photo_alter_news_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название ивента')),
                ('photo_of_event', models.ImageField(upload_to='media', verbose_name='Фото ивента')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('amount_of_guests', models.CharField(max_length=128, verbose_name='Количество гостей')),
                ('place_abilities', models.TextField(verbose_name='Возмонжости пространства')),
                ('extra_service', models.TextField(null=True, verbose_name='Доп услуги')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
    ]
