# Generated by Django 6.1 on 2026-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media', verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='photo1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo3',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo4',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo5',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo6',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 6'),
        ),
    ]
