# Generated by Django 6.1 on 2026-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_advertisement_banner_alter_products_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement_banner',
            name='link',
            field=models.TextField(default='', verbose_name='Ссылка на сайт или инст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='bio',
            field=models.TextField(default='', verbose_name='Био партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='project_photo',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото проекта'),
            preserve_default=False,
        ),
    ]
