# Generated by Django 6.1 on 2026-08-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_advertisement_banner_link_partners_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='amount_of_guests',
        ),
        migrations.RemoveField(
            model_name='masterclasses',
            name='place',
        ),
        migrations.AddField(
            model_name='events',
            name='allowed_amount',
            field=models.IntegerField(default=0, verbose_name='Доступно мест'),
        ),
        migrations.AddField(
            model_name='events',
            name='max_allowed',
            field=models.IntegerField(default=0, verbose_name='Максимум мест для гостей'),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='allowed_amount',
            field=models.IntegerField(default=0, verbose_name='Доступно мест'),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='max_allowed',
            field=models.IntegerField(default=0, verbose_name='Максимум мест для гостей'),
        ),
        migrations.AddField(
            model_name='products',
            name='allowed_amount',
            field=models.IntegerField(default=0, verbose_name='Доступно продуктов'),
        ),
        migrations.AddField(
            model_name='products',
            name='max_allowed',
            field=models.IntegerField(default=0, verbose_name='максимум продуктов'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pr_amount', models.IntegerField(default=0)),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
            options={
                'verbose_name': 'Корзина',
            },
        ),
    ]
