# Generated by Django 6.1 on 2026-08-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_events_amount_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_pr_amount',
            new_name='user_amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_masterclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.masterclasses'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
    ]
