# Generated by Django 6.1 on 2026-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_user_pr_amount_cart_user_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.TextField(default='', verbose_name='Секретный ключ. НЕ ТРОГАТЬ ЭТОТ ОБЬЕКТ'),
            preserve_default=False,
        ),
    ]
