# Generated by Django 6.1 on 2026-08-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
