# Generated by Django 6.1 on 2026-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_events_price_alter_masterclasses_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement_banner',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['name', 'photo_of_event', 'desc', 'allowed_amount', 'max_allowed', 'place_abilities', 'extra_service', 'price', 'my_order'], 'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'ordering': ['text', 'my_order'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='masterclasses',
            options={'ordering': ['photo', 'name', 'tamada', 'date', 'time', 'desc', 'price', 'allowed_amount', 'max_allowed', 'my_order'], 'verbose_name': 'Мастеркласс', 'verbose_name_plural': 'Мастерклассы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['photo', 'title', 'date', 'description', 'my_order'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['category_name', 'my_order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'photo6', 'price', 'allowed_amount', 'max_allowed', 'desc', 'size', 'details', 'product_category', 'my_order'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='events',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
