# Generated by Django 6.1 on 2026-08-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_advertisement_banner_delete_partners_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['my_order'], 'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterModelOptions(
            name='masterclasses',
            options={'ordering': ['my_order'], 'verbose_name': 'Мастеркласс', 'verbose_name_plural': 'Мастерклассы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['my_order'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['my_order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['my_order'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
