# Generated by Django 6.1 on 2026-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_events_options_alter_masterclasses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media', verbose_name='Фото сотрудника')),
                ('name', models.CharField(max_length=128, verbose_name='Имя сотрудника')),
                ('description', models.TextField(verbose_name='Описание для сотрудника')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['my_order'],
            },
        ),
    ]
