# Generated by Django 6.1 on 2026-09-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='max_allowed',
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя художника'),
        ),
        migrations.AddField(
            model_name='products',
            name='carry',
            field=models.TextField(default='', verbose_name='Рекомендации по уходу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(blank=True, max_length=256, verbose_name='Состояние продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.TextField(blank=True, verbose_name='Материал продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='period',
            field=models.TextField(blank=True, verbose_name='Период годов (от-до)'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='', max_length=256, verbose_name='Товар в единственном экземпляре или нет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='technique',
            field=models.TextField(blank=True, verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(verbose_name='Особенности кроя и отделки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название (Retail Product)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=128, verbose_name='Размер продукта'),
        ),
    ]
