# Generated by Django 6.1 on 2026-09-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_products_max_allowed_products_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото 6'),
        ),
    ]
