# Generated by Django 6.1 on 2026-09-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_products_photo1_alter_products_photo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='allowed_amount',
            new_name='max_allowed',
        ),
    ]
