# Generated by Django 6.1 on 2026-09-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_allowed_amount_products_max_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='max_allowed',
        ),
        migrations.RemoveField(
            model_name='masterclasses',
            name='max_allowed',
        ),
    ]
