# Generated by Django 6.1 on 2026-09-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_events_max_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='max_allowed',
            new_name='allowed_amount',
        ),
    ]
