# Generated by Django 6.1 on 2026-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_max_allowed_products_allowed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Если не загружено — на сайте показывается фото галереи по умолчанию', null=True, upload_to='media', verbose_name='Фото-баннер категории'),
        ),
    ]
