# Generated by Django 6.1 on 2026-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_productcategory_cover_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'ordering': ['my_order'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя автора отзыва'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_role',
            field=models.CharField(blank=True, max_length=128, verbose_name='Род деятельности автора'),
        ),
    ]
