# Generated by Django 6.1 on 2026-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_feedbacks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Короткое описание категории. Показывается под названием категории на её странице и на главной.', verbose_name='Текст категории'),
        ),
    ]
