# Generated by Django 6.1 on 2026-09-22 14:22

from django.db import migrations

ART_DESCRIPTION = 'Работы современных художников Узбекистана'


def seed_art_description(apps, schema_editor):
    ProductCategory = apps.get_model('app', 'ProductCategory')
    ProductCategory.objects.filter(category_name='Art', description='').update(description=ART_DESCRIPTION)


def unseed_art_description(apps, schema_editor):
    ProductCategory = apps.get_model('app', 'ProductCategory')
    ProductCategory.objects.filter(category_name='Art', description=ART_DESCRIPTION).update(description='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_productcategory_description'),
    ]

    operations = [
        migrations.RunPython(seed_art_description, unseed_art_description),
    ]
