# Generated by Django 6.1 on 2026-09-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_seed_art_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo6',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото продукта')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.products')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотки товара',
                'ordering': ['my_order'],
            },
        ),
    ]
