# Generated by Django 6.1 on 2026-09-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_images_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photo_of_event',
        ),
        migrations.RemoveField(
            model_name='masterclasses',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='photo',
        ),
        migrations.CreateModel(
            name='EventsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото ивента')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.events')),
            ],
            options={
                'verbose_name': 'Фото ивента',
                'verbose_name_plural': 'Фотки ивента',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='MasterclassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото мастеркласса')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.masterclasses')),
            ],
            options={
                'verbose_name': 'Фото мастеркласса',
                'verbose_name_plural': 'Фотки мастеркласса',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото новости')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.news')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фотки новости',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото рабочего')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.workers')),
            ],
            options={
                'verbose_name': 'Фото рабочего',
                'verbose_name_plural': 'Фотки рабочего',
                'ordering': ['my_order'],
            },
        ),
    ]
