# Generated by Django 6.1 on 2026-09-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_events_photo_of_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.RemoveField(
            model_name='products',
            name='period',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductConditionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=256, verbose_name='Состояние продукта')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='app.products')),
            ],
            options={
                'verbose_name': 'Состояние товара',
                'verbose_name_plural': 'Состояние товаров товаров товаоров',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField(blank=True, verbose_name='Материал продукта')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='app.products')),
            ],
            options={
                'verbose_name': 'Материал товара товара',
                'verbose_name_plural': 'Материалы товара товаоров',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPeriodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TextField(blank=True, verbose_name='Период годов (от-до)')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='app.products')),
            ],
            options={
                'verbose_name': 'Период товара',
                'verbose_name_plural': 'Пеироды товаоров',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSizeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128, verbose_name='Размер продукта')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='app.products')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товаров ',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatusField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Товар в единственном экземпляре или нет')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.products')),
            ],
            options={
                'verbose_name': 'Статус товара',
                'verbose_name_plural': 'Статус товара',
                'ordering': ['my_order'],
            },
        ),
    ]
