# Generated by Django 6.1 on 2026-09-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_products_condition_remove_products_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
        migrations.RemoveField(
            model_name='products',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='products',
            name='year',
        ),
        migrations.AddField(
            model_name='events',
            name='desc_en',
            field=models.TextField(default='', verbose_name='Описание на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='desc_uz',
            field=models.TextField(default='', verbose_name='Описание на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='extra_service_en',
            field=models.TextField(null=True, verbose_name='Доп услуги на англ'),
        ),
        migrations.AddField(
            model_name='events',
            name='extra_service_uz',
            field=models.TextField(null=True, verbose_name='Доп услуги на англ'),
        ),
        migrations.AddField(
            model_name='events',
            name='name_en',
            field=models.CharField(default='', max_length=256, verbose_name='Название ивента на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='name_uz',
            field=models.CharField(default='', max_length=256, verbose_name='Название ивента на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='place_abilities_en',
            field=models.TextField(default='', verbose_name='Возмонжости пространства на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='place_abilities_uz',
            field=models.TextField(default='', verbose_name='Возмонжости пространства на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя автора отзыва на англ'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_name_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя автора отзыва на узб'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_role_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Род деятельности автора на англ'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='author_role_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Род деятельности автора на узб'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='text_en',
            field=models.TextField(default='', verbose_name='Текст отзыва на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='text_uz',
            field=models.TextField(default='', verbose_name='Текст отзыва на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='desc_en',
            field=models.TextField(default='', verbose_name='Описание на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='desc_uz',
            field=models.TextField(default='', verbose_name='Описание на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='name_en',
            field=models.CharField(default='', max_length=128, verbose_name='Название мастеркласса на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='name_uz',
            field=models.CharField(default='', max_length=128, verbose_name='Название мастеркласса на узб '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='price_eur',
            field=models.IntegerField(default=1, verbose_name='Цена (в евро)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='price_usd',
            field=models.IntegerField(default=1, verbose_name='Цена (в долларах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='tamada_en',
            field=models.CharField(default='', max_length=128, verbose_name='Ведущий на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='tamada_uz',
            field=models.CharField(default='', max_length=128, verbose_name='Ведущий на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(default='', verbose_name='Описание на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(default=22, max_length=256, verbose_name='Заголовок на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_en',
            field=models.CharField(default='', max_length=128, verbose_name='Название категории на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_uz',
            field=models.CharField(default='', max_length=128, verbose_name='Название категории на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='carry_en',
            field=models.TextField(default='', verbose_name='Рекомендации по уходу на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='carry_uz',
            field=models.TextField(default='', verbose_name='Рекомендации по уходу на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='desc_en',
            field=models.TextField(default='', verbose_name='Описание продуктана англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='desc_uz',
            field=models.TextField(default='', verbose_name='Описание продукта на узб '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='details_en',
            field=models.TextField(default='', verbose_name='Особенности кроя и отделки на англ '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='details_uz',
            field=models.TextField(default='', verbose_name='Особенности кроя и отделки на узб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(default='', max_length=256, verbose_name='Название (Retail Product) на англ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name_uz',
            field=models.CharField(default='', max_length=256, verbose_name='Название (Retail Product) на узб'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArtProductAuthorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=256, verbose_name='Имя художника')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.products')),
            ],
            options={
                'verbose_name': 'Автор товара',
                'verbose_name_plural': 'Авторы товара',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtProductTechniqueField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.TextField(blank=True, verbose_name='Техника')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique', to='app.products')),
            ],
            options={
                'verbose_name': 'Год товара',
                'verbose_name_plural': 'Годы товара',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtProductYearField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=128, null=True, verbose_name='Год выпуска')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='app.products')),
            ],
            options={
                'verbose_name': 'Год товара',
                'verbose_name_plural': 'Годы товара',
                'ordering': ['my_order'],
            },
        ),
    ]
