# Generated by Django 6.1 on 2026-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_products_author_remove_products_technique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.TextField(default=0, verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_eur',
            field=models.TextField(verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_usd',
            field=models.TextField(verbose_name='Цена (в долларах)'),
        ),
    ]
