# Generated by Django 6.1 on 2026-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_events_price_eur_events_price_usd_alter_events_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproductauthorfield',
            name='author_eng',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя художника (на англ)'),
        ),
        migrations.AddField(
            model_name='artproductauthorfield',
            name='author_uz',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя художника (на узб)'),
        ),
        migrations.AddField(
            model_name='artproducttechniquefield',
            name='technique_eng',
            field=models.TextField(blank=True, verbose_name='Техника (на англ)'),
        ),
        migrations.AddField(
            model_name='artproducttechniquefield',
            name='technique_uz',
            field=models.TextField(blank=True, verbose_name='Техника (на узб)'),
        ),
        migrations.AddField(
            model_name='productconditionfield',
            name='condition_eng',
            field=models.CharField(blank=True, max_length=256, verbose_name='Состояние продукта (на англ)'),
        ),
        migrations.AddField(
            model_name='productconditionfield',
            name='condition_uz',
            field=models.CharField(blank=True, max_length=256, verbose_name='Состояние продукта (на узб)'),
        ),
        migrations.AddField(
            model_name='productmaterialfield',
            name='material_eng',
            field=models.TextField(blank=True, verbose_name='Материал продукта (на аннгл)'),
        ),
        migrations.AddField(
            model_name='productmaterialfield',
            name='material_uzb',
            field=models.TextField(blank=True, verbose_name='Материал продукта (на узб)'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_eur',
            field=models.CharField(default='', max_length=128, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_usd',
            field=models.CharField(default='', max_length=128, verbose_name='Цена в долларах'),
        ),
        migrations.AddField(
            model_name='productstatusfield',
            name='status_eng',
            field=models.CharField(blank=True, max_length=256, verbose_name='Товар в единственном экземпляре или нет (на англ)'),
        ),
        migrations.AddField(
            model_name='productstatusfield',
            name='status_uz',
            field=models.CharField(blank=True, max_length=256, verbose_name='Товар в единственном экземпляре или нет (на узб)'),
        ),
        migrations.AddField(
            model_name='workers',
            name='description_eng',
            field=models.TextField(default='', verbose_name='Описание для сотрудника (на англ)'),
        ),
        migrations.AddField(
            model_name='workers',
            name='description_uz',
            field=models.TextField(default='', verbose_name='Описание для сотрудника (на узб)'),
        ),
        migrations.AddField(
            model_name='workers',
            name='name_eng',
            field=models.CharField(default='', max_length=128, verbose_name='Имя сотрудника (на англ)'),
        ),
        migrations.AddField(
            model_name='workers',
            name='name_uz',
            field=models.CharField(default='', max_length=128, verbose_name='Имя сотрудника (на узб)'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='productstatusfield',
            name='status',
            field=models.CharField(blank=True, max_length=256, verbose_name='Товар в единственном экземпляре или нет'),
        ),
    ]
