# Generated by Django 6.1 on 2026-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_artproductauthorfield_author_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.TextField(verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price',
            field=models.TextField(default='', verbose_name='Цена'),
        ),
    ]
