# Generated by Django 6.1 on 2026-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_events_price_alter_masterclasses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description_eng',
            field=models.TextField(blank=True, default='', help_text='Короткое описание категории. Показывается под названием категории на её странице и на главной. (на англ)', verbose_name='Текст категории (на англ)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_uz',
            field=models.TextField(blank=True, default='', help_text='Короткое описание категории. Показывается под названием категории на её странице и на главной. (на узб)', verbose_name='Текст категории (на узб)'),
        ),
    ]
