# Generated by Django 6.1 on 2026-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_events_price_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price_eur',
            field=models.IntegerField(default=0, verbose_name='Цена (в евро)'),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='price_eur',
            field=models.IntegerField(default=0, verbose_name='Цена (в евро)'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_eur',
            field=models.IntegerField(default=0, max_length=128, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.IntegerField(verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price_usd',
            field=models.IntegerField(default=0, verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_usd',
            field=models.IntegerField(default=0, verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_usd',
            field=models.IntegerField(default=0, max_length=128, verbose_name='Цена в долларах'),
        ),
    ]
