# Generated by Django 6.1 on 2026-10-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_events_price_eur_masterclasses_price_eur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='masterclasses',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price_eur',
        ),
    ]
