# Generated by Django 6.1 on 2026-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_events_price_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price_eur',
            field=models.IntegerField(default=0, verbose_name='Цена (в евро)'),
        ),
        migrations.AddField(
            model_name='masterclasses',
            name='price_eur',
            field=models.IntegerField(default=0, verbose_name='Цена (в евро)'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_eur',
            field=models.IntegerField(default=0, max_length=128, verbose_name='Цена'),
        ),
    ]
