# Generated by Django 6.1 on 2026-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_events_price_eur_masterclasses_price_eur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_amount',
            new_name='choosed_amount',
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.TextField(default='', verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='masterclasses',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_eur',
            field=models.TextField(default='', verbose_name='Цена (в евро)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_usd',
            field=models.TextField(default='', verbose_name='Цена (в долларах)'),
        ),
    ]
