# Generated by Django 6.1 on 2026-10-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_user_amount_cart_choosed_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='choosed_amount',
            new_name='user_amount',
        ),
    ]
